### ISSUE TITLE
Extra line in completion candidates

### ISSUE THREAD

**Issue by gopar** [aaronjensen/company-flow#13]
Hey! First of all, huge thanks for writing this package \o/

The problem I'm having is that I get an extra line (Easier to show):

<img width="833" alt="screen shot 2018-02-25 at 1 32 31 pm" src="https://user-images.githubusercontent.com/1545083/36646748-c71ec728-1a30-11e8-8680-635650441606.png">

It shows up 90% of the time when doing completions.

Flow Version: 0.66.0

I'm very new to the JS world, so I might be doing something wrong? Not sure what other info to provide. Thanks!

**Comment by aaronjensen** [comment]
Thanks for the report @gopar can you try out https://github.com/aaronjensen/company-flow/commit/76ef585c70d2a3206c2eadf24ba61e59124c3a16 and let me know if that helps?

**Comment by gopar** [comment]
Thanks that worked \o/
