### ISSUE TITLE
how to use flow within node_modules?

### ISSUE THREAD

**Issue by faassen** [aaronjensen/company-flow#3]
The flow project recommends you install `flow-bin` inside a project in `node_modules`, not globally. I found emacs integration somewhere for flycheck that makes sure it uses the flow binary from `node_modules` instead of the globally installed one. Would it be possible to make this work with `company-flow` as well?

For reference here is the snippet I use:

```
(defun my/use-flow-from-node-modules ()
  (let* ((root (locate-dominating-file
                (or (buffer-file-name) default-directory)
                "node_modules"))
         (flow (and root
                    (expand-file-name "node_modules/flow-bin/vendor/flow"
                                      root))))
    (when (and flow (file-executable-p flow))
      (setq-local flycheck-javascript-flow-executable flow))))

(add-hook 'flycheck-mode-hook #'my/use-flow-from-node-modules)
```

**Comment by aaronjensen** [comment]
Hey @faassen yep, for sure. We'd need a customizable buffer local variable like `flycheck-javascript-flow-executable`, probably `company-flow-executable`. Would you like to take a stab at it?

**Comment by aaronjensen** [comment]
@faassen A new version should be up on MELPA shortly. Please give it a shot and let me know if it works for you.

**Comment by faassen** [comment]
Thank you so much, belatedly. I'll try to take a look in the near future.
