### ISSUE TITLE
Import auto completion issue

### ISSUE THREAD

**Issue by Ailrun** [aaronjensen/company-flow#9]
For case using `default` export like,

``` JSX
import React from 'react';

export function test() {
}

export default class Something extends React.Component/*::<*, *, *>*/ {
  constructor(props/*: **/) {
  }
}
```

and including such file, auto completion of import keyword doesn't work well.

``` JSX
import { |} from 'Something';
```

`|` is position of my cursor, then I try an autocompletion, it shows me `default` and `test`.

However, `default` case can't have any sense, because `import { default } from 'Something';` is just a error.

Is there any reason for this `default`?

**Comment by aaronjensen** [comment]
Hi @Ailrun,

Thank you for the report. This package is only responsible for using flow's own built-in completion mechanism. If there are bugs in it, I would encourage you to report them [here](https://github.com/facebook/flow). 

I'm going to close this out, but please open a new issue if you find any more issues with company-flow. Thanks!

**Comment by Ailrun** [comment]
@aaronjensen Could you tell me how I can check autocompletion of flow itself?

I try

``` shell
$ flow autocomplete 2 9 < src/Something.jsx
$ flow autocomplete 2 10 < src/Something.jsx
$ flow autocomplete src/Something.jsx 2 9
```

but nothing works.

(More accurately, `flow autocomplete 2 9 < src/Something.jsx` and `flow autocomplete 2 10 < src/Something.jsx` print `not enough type information to autocomplete` error. `2 9` is the position next to`import`.)

**Comment by aaronjensen** [comment]
Create a `bar.js` with:

```
// @flow
export default 3
```

Then run:

```
flow autocomplete --root . foo.js 1 10 <<<"import {  } from './bar'"
```

You should see:

```
$ flow autocomplete --root . foo.js 1 10 <<<"import {  } from './bar'"
default number
```

**Comment by aaronjensen** [comment]
By the way, `default` may be a valid auto-completion. This appears to at least compile:

```
import { default as bar } form './bar'
```

**Comment by Ailrun** [comment]
Thanks for your kind answer!
